# Generated by Django 4.2.3 on 2023-07-25 06:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ieltstest.answer_json.listening
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coachinginstitute', '0004_coachinginstitute_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Enter name of the Category', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Enter URL of this Category', null=True)),
                ('copyright', models.CharField(help_text='Enter copyright information for this category.', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Is this test approved for public?')),
                ('name', models.CharField(help_text='What is name of the Test? e.g. Cambridge Complete Test 11', max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level of this test', max_length=200)),
                ('category', models.ForeignKey(help_text='Select Category for this Test.', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.category')),
                ('institute', models.ForeignKey(help_text='Which institute has created this test?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachinginstitute.coachinginstitute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Test ideentifier name. e.g. Art and Science', max_length=200)),
                ('test', models.OneToOneField(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('section', models.CharField(choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3'), ('section4', 'Section 4')], help_text='What is section type?')),
                ('audio', models.FileField(help_text='Add Audio file for this section', upload_to='')),
                ('questions', ckeditor.fields.RichTextField(help_text='Add Question in HTML Format')),
                ('answers', models.JSONField(default=ieltstest.answer_json.listening.get_listening_answer_default, help_text='Add 40 answers in JSON format only.')),
                ('parent_test', models.ForeignKey(help_text='Select Parent Test for this section', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.listeningtest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
