# Generated by Django 4.2.3 on 2023-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], default=1, help_text='What is current status of this test?'),
            preserve_default=False,
        ),
    ]
