# Generated by Django 4.2.3 on 2023-07-25 17:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0002_listeningtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsection',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Add Question in HTML Format'),
        ),
    ]
