# Generated by Django 4.2.3 on 2023-07-26 16:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import ieltstest.answer_json.listening


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0003_alter_listeningsection_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningsection',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='listeningsection',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='listeningsection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='slug',
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?'),
        ),
        migrations.CreateModel(
            name='ListeningQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Questions 31-40', max_length=200)),
                ('questions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Add questions with form elements and correct ids')),
                ('answers', models.JSONField(default=ieltstest.answer_json.listening.get_listening_answer_default, help_text='Add answers for the questions above')),
                ('section', models.ForeignKey(help_text='Select Section for this Question Set', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.listeningsection')),
            ],
        ),
    ]
