# Generated by Django 4.2.3 on 2023-07-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0004_remove_listeningsection_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='name',
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='name',
            field=models.CharField(default=1, help_text='Test ideentifier name. e.g. Art and Science', max_length=200),
            preserve_default=False,
        ),
    ]
