# Generated by Django 4.2.3 on 2023-07-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0005_remove_listeningtest_name_listeningsection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='test',
            field=models.OneToOneField(blank=True, help_text='Select Parent Test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ieltstest.test'),
        ),
    ]
