# Generated by Django 4.2.3 on 2023-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0006_alter_listeningtest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this test active?'),
        ),
    ]
