# Generated by Django 4.2.3 on 2023-07-26 18:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ieltstest.answer_json.listening
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coachinginstitute', '0004_coachinginstitute_slug'),
        ('ieltstest', '0007_listeningtest_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('name', models.CharField(help_text='What is name of the book?', max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level of this test', max_length=200)),
                ('cover', models.ImageField(blank=True, help_text='Image of the Book Cover', null=True, upload_to='')),
                ('institute', models.ForeignKey(help_text='Which institute has created this test?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachinginstitute.coachinginstitute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='active',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.RemoveField(
            model_name='test',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='test',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='answers',
            field=models.JSONField(default=ieltstest.answer_json.listening.get_listening_answer_default, help_text='Add answers for the questions above'),
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add questions with form elements and correct ids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='category',
            field=models.ForeignKey(default=1, help_text='Select Category for this Individual Test.', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], default=1, help_text='What is current status of this test?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(help_text='Test 1', max_length=200),
        ),
        migrations.DeleteModel(
            name='ListeningQuestionSet',
        ),
    ]
