# Generated by Django 4.2.3 on 2023-07-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0008_book_remove_listeningtest_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='copyright',
            field=models.CharField(default=1, help_text='Enter copyright information for this category.', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='website',
            field=models.URLField(blank=True, help_text='Enter URL of this Category', null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
