# Generated by Django 4.2.3 on 2023-07-27 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0009_remove_listeningtest_category_book_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='test',
            field=models.OneToOneField(default=1, help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test'),
            preserve_default=False,
        ),
    ]
