# Generated by Django 4.2.3 on 2023-07-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0010_alter_listeningtest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='book',
            field=models.ForeignKey(default=1, help_text='Select book for this test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.book'),
            preserve_default=False,
        ),
    ]
