# Generated by Django 4.2.3 on 2023-07-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0011_test_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], default='draft', help_text='What is current status of this test?'),
            preserve_default=False,
        ),
    ]
