# Generated by Django 4.2.3 on 2023-07-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0012_listeningtest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListeningTest',
            new_name='ListeningModule',
        ),
    ]
