# Generated by Django 4.2.3 on 2023-07-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0013_rename_listeningtest_listeningmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeningsection',
            old_name='parent_test',
            new_name='listening_module',
        ),
    ]
