# Generated by Django 4.2.3 on 2023-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0014_rename_parent_test_listeningsection_listening_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningmodule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200),
        ),
    ]
