# Generated by Django 4.2.3 on 2023-07-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0015_alter_listeningmodule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningmodule',
            name='status',
        ),
    ]
