# Generated by Django 4.2.3 on 2023-07-28 05:39

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0017_listeningmodule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmodule',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True),
        ),
    ]
