# Generated by Django 4.2.3 on 2023-07-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0018_listeningmodule_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmodule',
            name='name',
            field=models.CharField(default='Listening Test 1', help_text='e.g. Listening Test March 2023', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(help_text='e.g. Practise Test 1', max_length=200),
        ),
    ]
