# Generated by Django 4.2.3 on 2023-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0019_listeningmodule_name_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Take this test if you would like to challenge yourself with band 9 targets', help_text='Add small book description.'),
            preserve_default=False,
        ),
    ]
