# Generated by Django 4.2.3 on 2023-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0020_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmodule',
            name='test_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('general', 'General'), ('both', 'Both')], default='both', help_text='What is test type for this?', max_length=200),
            preserve_default=False,
        ),
    ]
