# Generated by Django 4.2.3 on 2023-08-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0021_listeningmodule_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmodule',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, help_text='How many questions are there in this module?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, help_text='How many questions are there in this section?'),
            preserve_default=False,
        ),
    ]
