# Generated by Django 4.2.3 on 2023-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0024_listeningattempt_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningattempt',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
