# Generated by Django 4.2.3 on 2023-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0025_listeningattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningsection',
            name='audio',
        ),
        migrations.AddField(
            model_name='listeningmodule',
            name='audio',
            field=models.FileField(default=1, help_text='Add Audio file, all section merged in one audio', upload_to=''),
            preserve_default=False,
        ),
    ]
