# Generated by Django 4.2.3 on 2023-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0026_remove_listeningsection_audio_listeningmodule_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsection',
            name='audio_start_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='When should audio start for this section? 18.45 (18 seconds)', max_digits=20),
        ),
    ]
