# Generated by Django 4.2.3 on 2023-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0027_listeningsection_audio_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningattempt',
            name='bands',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
