# Generated by Django 4.2.3 on 2023-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0028_listeningattempt_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='How much time did user take to complete the test? In minutes.'),
        ),
    ]
