# Generated by Django 4.2.3 on 2023-08-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0029_listeningattempt_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSectionQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the question type. E.g. True/False, Match the topic, etc', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='question_type',
            field=models.ForeignKey(help_text='Choose question type for this section', null=True, on_delete=django.db.models.deletion.CASCADE, to='ieltstest.listeningsectionquestiontype'),
        ),
    ]
