# Generated by Django 4.2.3 on 2023-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0030_listeningsectionquestiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningattempt',
            name='bands',
            field=models.FloatField(default=0.0),
        ),
    ]
