# Generated by Django 4.2.3 on 2023-08-07 05:10

from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0031_alter_listeningattempt_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3'), ('section4', 'Section 4')], help_text='What is section type?')),
                ('name', models.CharField(help_text='Test ideentifier name. e.g. Art and Science', max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='How many questions are there in this section?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('test_type', models.CharField(choices=[('academic', 'Academic'), ('general', 'General'), ('both', 'Both')], help_text='What is test type for this?', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200)),
                ('name', models.CharField(help_text='e.g. Listening Test March 2023', max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='How many questions are there in this module?')),
                ('test', models.OneToOneField(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
