# Generated by Django 4.2.3 on 2023-08-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0032_readingsection_readingmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsection',
            name='reading_module',
            field=models.ForeignKey(default=1, help_text='Select parent reading module', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.readingmodule'),
            preserve_default=False,
        ),
    ]
