# Generated by Django 4.2.3 on 2023-08-07 06:15

import ckeditor_uploader.fields
from django.db import migrations, models
import ieltstest.answer_json.listening


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0033_readingsection_reading_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmodule',
            name='answers',
            field=models.JSONField(default=ieltstest.answer_json.listening.get_listening_answer_default, help_text='Add answers for the questions above'),
        ),
        migrations.AddField(
            model_name='readingmodule',
            name='passage',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add passage for this section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingmodule',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add questions with form elements and correct ids'),
            preserve_default=False,
        ),
    ]
