# Generated by Django 4.2.3 on 2023-08-08 03:50

import ckeditor_uploader.fields
from django.db import migrations, models
import ieltstest.answer_json.listening


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0034_readingmodule_answers_readingmodule_passage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmodule',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='readingmodule',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='readingmodule',
            name='questions',
        ),
        migrations.AddField(
            model_name='readingsection',
            name='answers',
            field=models.JSONField(default=ieltstest.answer_json.listening.get_listening_answer_default, help_text='Add answers for the questions above'),
        ),
        migrations.AddField(
            model_name='readingsection',
            name='passage',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add passage for this section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingsection',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add questions with form elements and correct ids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listeningsection',
            name='section',
            field=models.CharField(choices=[('Section 1', 'Section 1'), ('Section 2', 'Section 2'), ('Section 3', 'Section 3'), ('Section 4', 'Section 4')], help_text='What is section type?'),
        ),
        migrations.AlterField(
            model_name='readingsection',
            name='section',
            field=models.CharField(choices=[('Section 1', 'Section 1'), ('Section 2', 'Section 2'), ('Section 3', 'Section 3'), ('Section 4', 'Section 4')], help_text='What is section type?'),
        ),
    ]
