# Generated by Django 4.2.3 on 2023-08-09 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ieltstest', '0035_remove_readingmodule_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated')], default='In Progress', help_text='What is currect status of this attempt?')),
                ('evaluation', models.JSONField(blank=True, help_text='Evaluation of the attempt', null=True)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='How much time did user take to complete the test? In minutes.')),
                ('bands', models.FloatField(default=0.0)),
                ('module', models.ForeignKey(help_text='Select Parent module for this attempt', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.readingmodule')),
                ('user', models.ForeignKey(help_text='Select user for the attempt', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
