# Generated by Django 4.2.3 on 2023-08-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0036_readingattempt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListeningSectionQuestionType',
            new_name='QuestionType',
        ),
    ]
