# Generated by Django 4.2.3 on 2023-08-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0037_rename_listeningsectionquestiontype_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsection',
            name='question_type',
            field=models.ForeignKey(help_text='Choose question type for this section', null=True, on_delete=django.db.models.deletion.CASCADE, to='ieltstest.questiontype'),
        ),
    ]
