# Generated by Django 4.2.3 on 2023-08-19 20:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0039_writingmodule_writingsection_writingattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsection',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='Add questions with images for writing module'),
            preserve_default=False,
        ),
    ]
