# Generated by Django 4.2.3 on 2023-08-21 06:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0040_writingsection_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsection',
            name='task',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, help_text='Add task 1/2 with images for writing module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='writingsection',
            name='questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Add questions/text area for user to write answer'),
        ),
    ]
