# Generated by Django 4.2.3 on 2023-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0041_writingsection_task_alter_writingsection_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingattempt',
            name='answers',
            field=models.JSONField(blank=True, help_text='Answers that is attempted by user', null=True),
        ),
        migrations.AddField(
            model_name='readingattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingattempt',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
