# Generated by Django 4.2.3 on 2023-08-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0043_writingattempt_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingattempt',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='writingattempt',
            name='incorrect_answers',
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='openai_bands',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingattempt',
            name='openai_evaluation',
            field=models.BooleanField(default=False),
        ),
    ]
