# Generated by Django 4.2.3 on 2023-08-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0045_writingattempt_evaluation_bands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingattempt',
            name='openai_bands',
        ),
        migrations.RemoveField(
            model_name='writingattempt',
            name='openai_evaluation',
        ),
    ]
