# Generated by Django 4.2.3 on 2023-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0046_remove_writingattempt_openai_bands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingattempt',
            name='temp_text_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='writingsection',
            name='section',
            field=models.CharField(choices=[('Task 1', 'Task 1'), ('Task 2', 'Task 2')], help_text='What is section type?'),
        ),
    ]
