# Generated by Django 4.2.3 on 2023-08-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0048_alter_writingattempt_evaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingattempt',
            name='temp_text_field',
        ),
    ]
