# Generated by Django 4.2.3 on 2023-08-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0050_speakingsection_speakingmodule_speakingattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingsection',
            name='speaking_module',
            field=models.ForeignKey(help_text='Select parent writing module', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.speakingmodule'),
        ),
    ]
