# Generated by Django 4.2.3 on 2023-08-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0051_alter_speakingsection_speaking_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Add speaking section question.', max_length=300)),
                ('help_text', models.TextField(blank=True, help_text='Add helper text for this question', null=True)),
                ('speaking_section', models.ForeignKey(help_text='Select parent speaking section', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.speakingsection')),
            ],
        ),
    ]
