# Generated by Django 4.2.3 on 2023-08-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0052_speakingsectionquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingmodule',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='writingmodule',
            name='total_questions',
        ),
    ]
