# Generated by Django 4.2.3 on 2023-08-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0053_remove_speakingmodule_total_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingsection',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='writingsection',
            name='total_questions',
        ),
    ]
