# Generated by Django 4.2.3 on 2023-08-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0054_remove_speakingsection_total_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingsectionquestion',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
