# Generated by Django 4.2.3 on 2023-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0055_speakingsectionquestion_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='answers',
            field=models.JSONField(blank=True, help_text='Answers that is attempted by user', null=True),
        ),
    ]
