# Generated by Django 4.2.3 on 2023-09-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0056_speakingattempt_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAttemptAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Add Audio file for the speaking attempt', upload_to='')),
                ('timestamps', models.JSONField(blank=True, help_text='Timestamps for each question in the audio', null=True)),
                ('attempt', models.ForeignKey(help_text='Select attempt for this audio', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.speakingattempt')),
                ('section', models.ForeignKey(help_text='Select parent speaking section', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.speakingsection')),
            ],
        ),
    ]
