# Generated by Django 4.2.3 on 2023-10-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0057_speakingattemptaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingattempt',
            name='answers',
        ),
    ]
