# Generated by Django 4.2.3 on 2023-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0058_remove_speakingattempt_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattemptaudio',
            name='audio_text',
            field=models.TextField(help_text='Text converted from the original audio', null=True),
        ),
    ]
