# Generated by Django 4.2.3 on 2023-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0061_writingattempt_evaluation_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='merged_audio',
            field=models.FileField(blank=True, help_text='Merged Audio File from all the audios', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='speakingattemptaudio',
            name='audio_text',
            field=models.TextField(blank=True, help_text='Text converted from the original audio', null=True),
        ),
    ]
