# Generated by Django 4.2.3 on 2023-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0062_speakingattempt_merged_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='merged_timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
