# Generated by Django 4.2.3 on 2023-12-06 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0065_alter_fulltestattempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingsectionquestion',
            name='help_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Add helper text for this question', null=True),
        ),
    ]
