# Generated by Django 4.2.3 on 2023-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0066_alter_speakingsectionquestion_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('error-check', 'Perform Error Check'), ('error-found', 'Error Found'), ('published', 'Published'), ('discard', 'Discard')], default='in-progress', max_length=50),
        ),
    ]
