# Generated by Django 4.2.3 on 2023-12-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0067_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningsection',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='readingsection',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='writingsection',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='listeningmodule',
            name='audio',
            field=models.FileField(blank=True, help_text='Add Audio file, all section merged in one audio', null=True, upload_to=''),
        ),
    ]
