# Generated by Django 4.2.3 on 2023-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0068_remove_listeningsection_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='academic_cover',
        ),
        migrations.AddField(
            model_name='book',
            name='general_cover',
            field=models.ImageField(blank=True, help_text='Image of the Book Cover', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], default='in-progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='listeningmodule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200),
        ),
        migrations.AlterField(
            model_name='readingmodule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200),
        ),
        migrations.AlterField(
            model_name='speakingmodule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?'),
        ),
        migrations.AlterField(
            model_name='writingmodule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('modules-created', 'Modules Created'), ('stage-1', 'Stage 1 Completed'), ('stage-2', 'Stage 2 Completed'), ('needs-attention', 'Needs Attention'), ('published', 'Published'), ('discard', 'Discard')], help_text='What is current status of this test?', max_length=200),
        ),
    ]
