# Generated by Django 4.2.3 on 2023-12-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0069_rename_cover_book_academic_cover_book_general_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakingsectionquestion',
            old_name='weight',
            new_name='priority',
        ),
    ]
