# Generated by Django 4.2.3 on 2023-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0070_rename_weight_speakingsectionquestion_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
