# Generated by Django 4.2.3 on 2024-01-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0071_book_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningmodule',
            name='test',
            field=models.ForeignKey(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test'),
        ),
        migrations.AlterField(
            model_name='readingmodule',
            name='test',
            field=models.ForeignKey(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test'),
        ),
        migrations.AlterField(
            model_name='speakingmodule',
            name='test',
            field=models.ForeignKey(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test'),
        ),
        migrations.AlterField(
            model_name='writingmodule',
            name='test',
            field=models.ForeignKey(help_text='Select Parent Test', on_delete=django.db.models.deletion.CASCADE, to='ieltstest.test'),
        ),
    ]
