# Generated by Django 4.2.3 on 2024-01-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0072_alter_listeningmodule_test_alter_readingmodule_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltestattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='listeningattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='readingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='speakingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
    ]
