# Generated by Django 4.2.3 on 2024-01-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0073_alter_fulltestattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='fluency_and_coherence_bands',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speakingattempt',
            name='grammatical_range_and_accuracy_bands',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speakingattempt',
            name='lexical_resource_bands',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speakingattempt',
            name='pronunciation_bands',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fulltestattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready'), ('Evaluated', 'Evaluated')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='listeningattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready'), ('Evaluated', 'Evaluated')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='readingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready'), ('Evaluated', 'Evaluated')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='speakingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready'), ('Evaluated', 'Evaluated')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready'), ('Evaluated', 'Evaluated')], default='Not Started', help_text='What is currect status of this attempt?'),
        ),
    ]
