# Generated by Django 4.2.3 on 2024-01-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0074_speakingattempt_fluency_and_coherence_bands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
