# Generated by Django 4.2.3 on 2024-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0075_speakingattempt_is_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='audio_text',
            field=models.TextField(blank=True, help_text='Text converted from the original audio', null=True),
        ),
    ]
