# Generated by Django 4.2.3 on 2024-01-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0076_speakingattempt_audio_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeakingAttemptAudio',
        ),
    ]
