# Generated by Django 4.2.3 on 2024-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0077_delete_speakingattemptaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='internal_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Transcribed', 'Transcribed'), ('Evaluated', 'Evaluated'), ('Ready', 'Ready')], default='Completed', max_length=200),
        ),
    ]
