# Generated by Django 4.2.3 on 2024-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0079_alter_speakingattempt_internal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingattempt',
            name='internal_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Transcribed', 'Transcribed'), ('Evaluated', 'Evaluated'), ('Verify Bands', 'Verify Bands'), ('Ready', 'Ready')], default='Created', max_length=200),
        ),
    ]
