# Generated by Django 4.2.3 on 2024-01-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0080_alter_speakingattempt_internal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingattempt',
            name='cropped_audio',
            field=models.FileField(blank=True, help_text='Cropped Audio File that is used for grading', null=True, upload_to=''),
        ),
    ]
