# Generated by Django 4.2.3 on 2023-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, help_text='Is this school verified for green tick?')),
                ('name', models.CharField(help_text='Name of this institute.', max_length=200)),
                ('email', models.EmailField(help_text='Primary email of this institute.', max_length=254)),
                ('phone', models.CharField(help_text='Primary phone number of this institute.', max_length=50)),
                ('logo', models.ImageField(help_text='Logo of this institute', upload_to='')),
            ],
        ),
    ]
