# Generated by Django 4.2.3 on 2023-07-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachinginstitute', '0002_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='institute',
            field=models.ForeignKey(help_text='Is this Tutor part of any Coaching Institute?', on_delete=django.db.models.deletion.CASCADE, to='coachinginstitute.coachinginstitute'),
        ),
    ]
