# Generated by Django 4.2.3 on 2023-07-23 21:03

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coachinginstitute', '0003_alter_tutor_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachinginstitute',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True),
        ),
    ]
