# Generated by Django 4.2.3 on 2023-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Is user email verified?'),
        ),
    ]
