# Generated by Django 4.2.3 on 2023-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.PositiveIntegerField(blank=True, help_text='Verification code sent to user email', null=True),
        ),
    ]
