# Generated by Django 4.2.3 on 2023-07-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coachinginstitute', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(blank=True, help_text='Is this student enrolled at any coaching institute?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachinginstitute.coachinginstitute')),
                ('user', models.OneToOneField(help_text='Select base user for this student.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
