# Generated by Django 4.2.3 on 2023-07-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachinginstitute', '0003_alter_tutor_institute'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(blank=True, help_text='Is this student enrolled at any coaching institute?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coachinginstitute.coachinginstitute'),
        ),
    ]
