# Generated by Django 4.2.3 on 2023-07-23 20:21

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=20, max_length=20, unique=True),
        ),
    ]
