# Generated by Django 4.2.3 on 2023-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('academic', 'Academic'), ('general', 'General')], default='academic', help_text='What test type is student preparing for?', max_length=200),
        ),
    ]
