# Generated by Django 4.2.3 on 2023-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bands_target',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=2),
        ),
    ]
