# Generated by Django 4.2.3 on 2023-11-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_bands_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bands_target',
            new_name='bandsTarget',
        ),
    ]
