# Generated by Django 4.2.3 on 2023-11-25 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_bands_target_student_bandstarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallPerformanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_feedback', models.TextField(blank=True, help_text='Write your feedback for this student.', null=True)),
                ('student', models.OneToOneField(help_text='Select student for this feedback.', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
