# Generated by Django 4.2.3 on 2023-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_overallperformancefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallperformancefeedback',
            name='total_attempts',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='How many attempts did this user had in total for this feedback?', max_digits=5),
        ),
    ]
