# Generated by Django 4.2.3 on 2023-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
