# Generated by Django 4.2.3 on 2023-12-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_issue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
