# Generated by Django 4.2.3 on 2024-01-11 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_commentmain_commentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('category', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('dashboard', 'Dashboard'), ('other', 'Other')], default='other', max_length=100)),
                ('info', models.CharField(help_text='Info about this AI response', max_length=500)),
                ('input', models.TextField(help_text='Input to the AI')),
                ('response', models.TextField(help_text='Response from the AI')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
