# Generated by Django 4.2.3 on 2024-01-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_airesponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='info',
        ),
    ]
