# Generated by Django 4.2.3 on 2024-01-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_airesponse_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
    ]
